### ISSUE TITLE
Generic error page

### ISSUE THREAD

**Issue by Stephanie-A** [carllcox/VIP#26]
Make generic error page to catch any error heroku will throw
1. accessing page without logging in

**Comment by RahulN97** [comment]
Don't need error page since we should be handling errors with either alerts or by automatically redirecting the page.

The action of accessing pages without logging in cannot be intercepted from Heroku. This should be handled within the code in some other way.

Closing the issue for now since an ideal fix would require more time/development, and our current fixes are sufficient for the demo.
